name: Linter, Formatter, Type Checker

on:
  push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v4
        - uses: actions/setup-node@v4
          with:
            cache: 'pnpm'
        - run: pnpm install --frozen-lockfile
        - run: pnpm run lint
        - run: pnpm run check-types
        - run: pnpm run test