name: Linter, Formatter, Type Checker

on:
  push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v4
        - uses: actions/setup-node@v4
          with:
            cache: 'pnpm'

    install:
      runs-on: ubuntu-latest
      steps:
        - run: pnpm install --frozen-lockfile

    lint:
      runs-on: ubuntu-latest
      steps:
        - run: pnpm run lint

    check-types:
      runs-on: ubuntu-latest
      steps:
        - run: pnpm run check-types

    test:
      runs-on: ubuntu-latest
      steps:
        - run: pnpm run test